excerpt_separator: ""
highlighter: "rouge"
markdown: kramdown
url: http://sandrobraendli.github.io
title: Sandro's Personal Blog
tagline: A log of everyday life
description: My awesome new site
paginate: 5
